// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: custom_clock_2

#ifndef _CUSTOM_CLOCK_2_UI_H
#define _CUSTOM_CLOCK_2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_clock.h"
#include "ui_terminal.h"
#include "ui_settings.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1355446393);    // assets/light-bulb_32_w.png
LV_IMG_DECLARE(ui_img_01d_png);    // assets/01d.png
LV_IMG_DECLARE(ui_img_slider_32_png);    // assets/slider_32.png
LV_IMG_DECLARE(ui_img_exit_32_png);    // assets/exit_32.png
LV_IMG_DECLARE(ui_img_1322430811);    // assets/light-bulb_32.png
LV_IMG_DECLARE(ui_img_terminal_32_png);    // assets/terminal_32.png
LV_IMG_DECLARE(ui_img_blynk_disconnected_50_png);    // assets/blynk_disconnected_50.png
LV_IMG_DECLARE(ui_img_blynk_connected_50_png);    // assets/blynk_connected_50.png
LV_IMG_DECLARE(ui_img_calendar_32_png);    // assets/calendar_32.png
LV_IMG_DECLARE(ui_img_alarm_32_png);    // assets/alarm_32.png
LV_IMG_DECLARE(ui_img_audio_32_png);    // assets/audio_32.png
LV_IMG_DECLARE(ui_img_network_32_png);    // assets/network_32.png
LV_IMG_DECLARE(ui_img_folder_32_png);    // assets/folder_32.png
LV_IMG_DECLARE(ui_img_blynk_50_png);    // assets/blynk_50.png
LV_IMG_DECLARE(ui_img_icon_24_png);    // assets/icon_24.png
LV_IMG_DECLARE(ui_img_icon_32_png);    // assets/icon_32.png
LV_IMG_DECLARE(ui_img_icon_48_png);    // assets/icon_48.png
LV_IMG_DECLARE(ui_img_icon_50_png);    // assets/icon_50.png
LV_IMG_DECLARE(ui_img_841028446);    // assets/light-bulb_64.png
LV_IMG_DECLARE(ui_img_wifi_32_png);    // assets/wifi_32.png
LV_IMG_DECLARE(ui_img_01n_png);    // assets/01n.png
LV_IMG_DECLARE(ui_img_02d_png);    // assets/02d.png
LV_IMG_DECLARE(ui_img_02n_png);    // assets/02n.png
LV_IMG_DECLARE(ui_img_03d_png);    // assets/03d.png
LV_IMG_DECLARE(ui_img_03n_png);    // assets/03n.png
LV_IMG_DECLARE(ui_img_04d_png);    // assets/04d.png
LV_IMG_DECLARE(ui_img_04n_png);    // assets/04n.png
LV_IMG_DECLARE(ui_img_09d_png);    // assets/09d.png
LV_IMG_DECLARE(ui_img_09n_png);    // assets/09n.png
LV_IMG_DECLARE(ui_img_10d_png);    // assets/10d.png
LV_IMG_DECLARE(ui_img_10n_png);    // assets/10n.png
LV_IMG_DECLARE(ui_img_11d_png);    // assets/11d.png
LV_IMG_DECLARE(ui_img_11n_png);    // assets/11n.png
LV_IMG_DECLARE(ui_img_13d_png);    // assets/13d.png
LV_IMG_DECLARE(ui_img_13n_png);    // assets/13n.png
LV_IMG_DECLARE(ui_img_50d_png);    // assets/50d.png
LV_IMG_DECLARE(ui_img_50n_png);    // assets/50n.png

// FONTS
LV_FONT_DECLARE(ui_font_digital128);
LV_FONT_DECLARE(ui_font_digital48);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
