// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: custom_clock_2

#include "ui.h"

#include "timekeeper.h"

lv_obj_t * ui_clock = NULL;
lv_obj_t * ui_LED_Toggle_Button2 = NULL;
lv_obj_t * ui_clockFace = NULL;
lv_obj_t * ui_clockFaceM = NULL;
lv_obj_t * ui_clockFaceC = NULL;
lv_obj_t * ui_clockFaceS = NULL;
lv_obj_t * ui_clockFaceH = NULL;
lv_obj_t * ui_weather = NULL;
lv_obj_t * ui_weatherIcon = NULL;
lv_obj_t * ui_weatherTemp = NULL;
lv_obj_t * ui_Button8 = NULL;

// update functions
void ui_update_clock_face()
{
    DateTime time = timekeeper.time();

    lv_label_set_text_fmt(ui_clockFaceH, "%02d", time.hour());
    lv_label_set_text_fmt(ui_clockFaceM, "%02d", time.minute());
    lv_label_set_text_fmt(ui_clockFaceS, "%02d", time.second());
}

void ui_update_weather_panel(bool valid, const char *imgID, uint8_t temp)
{
    if (!valid)
    {
        // Hide the weather panel
        lv_obj_add_flag(ui_weather, LV_OBJ_FLAG_HIDDEN);
        return;
    }

    // Show the weather panel
    lv_obj_clear_flag(ui_weather, LV_OBJ_FLAG_HIDDEN);

    // Set temperature
    lv_label_set_text_fmt(ui_weatherTemp, "%u°", temp);

    // Weather icon lookup
    const lv_img_dsc_t *weatherIcon = nullptr;

    if (strcmp(imgID, "01d") == 0) weatherIcon = &ui_img_01d_png;
    else if (strcmp(imgID, "01n") == 0) weatherIcon = &ui_img_01n_png;
    else if (strcmp(imgID, "02d") == 0) weatherIcon = &ui_img_02d_png;
    else if (strcmp(imgID, "02n") == 0) weatherIcon = &ui_img_02n_png;
    else if (strcmp(imgID, "03d") == 0) weatherIcon = &ui_img_03d_png;
    else if (strcmp(imgID, "03n") == 0) weatherIcon = &ui_img_03n_png;
    else if (strcmp(imgID, "04d") == 0) weatherIcon = &ui_img_04d_png;
    else if (strcmp(imgID, "04n") == 0) weatherIcon = &ui_img_04n_png;
    else if (strcmp(imgID, "09d") == 0) weatherIcon = &ui_img_09d_png;
    else if (strcmp(imgID, "09n") == 0) weatherIcon = &ui_img_09n_png;
    else if (strcmp(imgID, "10d") == 0) weatherIcon = &ui_img_10d_png;
    else if (strcmp(imgID, "10n") == 0) weatherIcon = &ui_img_10n_png;
    else if (strcmp(imgID, "11d") == 0) weatherIcon = &ui_img_11d_png;
    else if (strcmp(imgID, "11n") == 0) weatherIcon = &ui_img_11n_png;
    else if (strcmp(imgID, "13d") == 0) weatherIcon = &ui_img_13d_png;
    else if (strcmp(imgID, "13n") == 0) weatherIcon = &ui_img_13n_png;
    else if (strcmp(imgID, "50d") == 0) weatherIcon = &ui_img_50d_png;
    else if (strcmp(imgID, "50n") == 0) weatherIcon = &ui_img_50n_png;

    if (weatherIcon != nullptr)
        lv_img_set_src(ui_weatherIcon, weatherIcon);
}

// event funtions
void ui_event_LED_Toggle_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onWhiteLEDButtonToggle(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_settings_screen_init);
    }
}

// build funtions

void ui_clock_screen_init(void)
{
    ui_clock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clock, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LED_Toggle_Button2 = lv_btn_create(ui_clock);
    lv_obj_set_width(ui_LED_Toggle_Button2, 50);
    lv_obj_set_height(ui_LED_Toggle_Button2, 50);
    lv_obj_set_x(ui_LED_Toggle_Button2, -10);
    lv_obj_set_y(ui_LED_Toggle_Button2, 10);
    lv_obj_set_align(ui_LED_Toggle_Button2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_LED_Toggle_Button2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LED_Toggle_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LED_Toggle_Button2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LED_Toggle_Button2, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LED_Toggle_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_LED_Toggle_Button2, &ui_img_1355446393, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_LED_Toggle_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_LED_Toggle_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LED_Toggle_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LED_Toggle_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LED_Toggle_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LED_Toggle_Button2, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_LED_Toggle_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_LED_Toggle_Button2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_LED_Toggle_Button2, &ui_img_1355446393, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_LED_Toggle_Button2, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_LED_Toggle_Button2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_LED_Toggle_Button2, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_LED_Toggle_Button2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_LED_Toggle_Button2, 1, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_clockFace = lv_obj_create(ui_clock);
    lv_obj_remove_style_all(ui_clockFace);
    lv_obj_set_width(ui_clockFace, 330);
    lv_obj_set_height(ui_clockFace, 120);
    lv_obj_set_align(ui_clockFace, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_clockFace, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clockFaceM = lv_label_create(ui_clockFace);
    lv_obj_set_width(ui_clockFaceM, 122);
    lv_obj_set_height(ui_clockFaceM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clockFaceM, 153);
    lv_obj_set_y(ui_clockFaceM, 0);
    lv_obj_set_align(ui_clockFaceM, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_clockFaceM, "00");
    lv_obj_clear_flag(ui_clockFaceM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_clockFaceM, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clockFaceM, &ui_font_digital128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockFaceC = lv_label_create(ui_clockFace);
    lv_obj_set_width(ui_clockFaceC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clockFaceC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clockFaceC, 132);
    lv_obj_set_y(ui_clockFaceC, 0);
    lv_obj_set_align(ui_clockFaceC, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_clockFaceC, ":");
    lv_obj_clear_flag(ui_clockFaceC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_clockFaceC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clockFaceC, &ui_font_digital128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockFaceS = lv_label_create(ui_clockFace);
    lv_obj_set_width(ui_clockFaceS, 46);
    lv_obj_set_height(ui_clockFaceS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clockFaceS, 275);
    lv_obj_set_y(ui_clockFaceS, 26);
    lv_obj_set_align(ui_clockFaceS, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_clockFaceS, "00");
    lv_obj_clear_flag(ui_clockFaceS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_clockFaceS, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clockFaceS, &ui_font_digital48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockFaceH = lv_label_create(ui_clockFace);
    lv_obj_set_width(ui_clockFaceH, 122);
    lv_obj_set_height(ui_clockFaceH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clockFaceH, 10);
    lv_obj_set_y(ui_clockFaceH, 0);
    lv_obj_set_align(ui_clockFaceH, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_clockFaceH, "00");
    lv_obj_clear_flag(ui_clockFaceH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_clockFaceH, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clockFaceH, &ui_font_digital128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_obj_create(ui_clock);
    lv_obj_remove_style_all(ui_weather);
    lv_obj_set_width(ui_weather, 150);
    lv_obj_set_height(ui_weather, 84);
    lv_obj_clear_flag(ui_weather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weatherIcon = lv_img_create(ui_weather);
    lv_img_set_src(ui_weatherIcon, &ui_img_01d_png);
    lv_obj_set_width(ui_weatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_weatherIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weatherTemp = lv_label_create(ui_weather);
    lv_obj_set_width(ui_weatherTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherTemp, 50);
    lv_obj_set_y(ui_weatherTemp, 20);
    lv_label_set_text(ui_weatherTemp, "72°");
    lv_obj_set_style_text_align(ui_weatherTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherTemp, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_btn_create(ui_clock);
    lv_obj_set_width(ui_Button8, 40);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_x(ui_Button8, -65);
    lv_obj_set_y(ui_Button8, 10);
    lv_obj_set_align(ui_Button8, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button8, &ui_img_slider_32_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LED_Toggle_Button2, ui_event_LED_Toggle_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);

    // Update to initial values
    ui_update_clock_face();
    ui_update_weather_panel(false, nullptr, 0);
}

void ui_clock_screen_destroy(void)
{
    if(ui_clock) lv_obj_del(ui_clock);

    // NULL screen variables
    ui_clock = NULL;
    ui_LED_Toggle_Button2 = NULL;
    ui_clockFace = NULL;
    ui_clockFaceM = NULL;
    ui_clockFaceC = NULL;
    ui_clockFaceS = NULL;
    ui_clockFaceH = NULL;
    ui_weather = NULL;
    ui_weatherIcon = NULL;
    ui_weatherTemp = NULL;
    ui_Button8 = NULL;

}