// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: custom_clock_2

#ifndef UI_CLOCK_H
#define UI_CLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clock
extern void ui_clock_screen_init(void);
extern void ui_clock_screen_destroy(void);
extern lv_obj_t * ui_clock;
extern void ui_event_LED_Toggle_Button2(lv_event_t * e);
extern lv_obj_t * ui_LED_Toggle_Button2;
extern lv_obj_t * ui_clockFace;
extern lv_obj_t * ui_clockFaceM;
extern lv_obj_t * ui_clockFaceC;
extern lv_obj_t * ui_clockFaceS;
extern lv_obj_t * ui_clockFaceH;
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_weatherIcon;
extern lv_obj_t * ui_weatherTemp;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

