// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: custom_clock_2

#include "ui.h"

void onWhiteLEDButtonToggle(lv_event_t * e)
{
    // code here
}

void terminalSendCommand(lv_event_t * e)
{
	// Your code here
}

void onLEDColorWheelUpdate(lv_event_t * e)
{
	// Your code here
}

void onLEDSaturationSliderUpdate(lv_event_t * e)
{
	// Your code here
}

void onLEDButtonToggle(lv_event_t * e)
{
	// Your code here
}

void onLEDBrightnessSliderUpdate(lv_event_t * e)
{
	// Your code here
}

void handleBlynkButtonPressed(lv_event_t * e)
{
	// Your code here
}
