// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: custom_clock_2

#include "ui.h"

lv_obj_t * ui_settings = NULL;
lv_obj_t * ui_LED_Color_Wheel = NULL;
lv_obj_t * ui_LED_Saturation_Slider = NULL;
lv_obj_t * ui_LED_Toggle_Button = NULL;
lv_obj_t * ui_Light_Control_Title = NULL;
lv_obj_t * ui_Switch_to_clock = NULL;
lv_obj_t * ui_LED_Brightness_Slider = NULL;
lv_obj_t * ui_Go_to_terminal = NULL;
lv_obj_t * ui_Blynk_connect = NULL;
lv_obj_t * ui_Go_to_time_settings = NULL;
lv_obj_t * ui_Go_to_alarm_settings = NULL;
lv_obj_t * ui_Go_to_audio_settings = NULL;
lv_obj_t * ui_Go_to_network_settings = NULL;
lv_obj_t * ui_Go_to_files = NULL;
lv_obj_t * ui_Settings_title = NULL;
// event funtions
void ui_event_LED_Color_Wheel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onLEDColorWheelUpdate(e);
    }
}

void ui_event_LED_Saturation_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onLEDSaturationSliderUpdate(e);
    }
}

void ui_event_LED_Toggle_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onLEDButtonToggle(e);
    }
}

void ui_event_Switch_to_clock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_clock, LV_SCR_LOAD_ANIM_OUT_TOP, 500, 0, &ui_clock_screen_init);
    }
}

void ui_event_LED_Brightness_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onLEDBrightnessSliderUpdate(e);
    }
}

void ui_event_Go_to_terminal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_terminal, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_terminal_screen_init);
    }
}

void ui_event_Blynk_connect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        handleBlynkButtonPressed(e);
    }
}

void ui_event_Go_to_time_settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_terminal, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_terminal_screen_init);
    }
}

// build funtions

void ui_settings_screen_init(void)
{
    ui_settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LED_Color_Wheel = lv_colorwheel_create(ui_settings, true);
    lv_obj_set_width(ui_LED_Color_Wheel, 150);
    lv_obj_set_height(ui_LED_Color_Wheel, 150);
    lv_obj_set_align(ui_LED_Color_Wheel, LV_ALIGN_CENTER);

    ui_LED_Saturation_Slider = lv_slider_create(ui_settings);
    lv_slider_set_value(ui_LED_Saturation_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LED_Saturation_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_LED_Saturation_Slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LED_Saturation_Slider, 150);
    lv_obj_set_height(ui_LED_Saturation_Slider, 10);
    lv_obj_set_x(ui_LED_Saturation_Slider, 0);
    lv_obj_set_y(ui_LED_Saturation_Slider, 110);
    lv_obj_set_align(ui_LED_Saturation_Slider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LED_Saturation_Slider, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LED_Saturation_Slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LED_Saturation_Slider, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LED_Saturation_Slider, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LED_Saturation_Slider, lv_color_hex(0x888888), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LED_Saturation_Slider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LED_Saturation_Slider, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LED_Saturation_Slider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LED_Saturation_Slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LED_Saturation_Slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LED_Toggle_Button = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_LED_Toggle_Button, 50);
    lv_obj_set_height(ui_LED_Toggle_Button, 50);
    lv_obj_set_align(ui_LED_Toggle_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LED_Toggle_Button, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LED_Toggle_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LED_Toggle_Button, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LED_Toggle_Button, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LED_Toggle_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_LED_Toggle_Button, &ui_img_1322430811, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_LED_Toggle_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_LED_Toggle_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LED_Toggle_Button, 25, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_LED_Toggle_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_LED_Toggle_Button, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_LED_Toggle_Button, &ui_img_1322430811, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_LED_Toggle_Button, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_LED_Toggle_Button, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Light_Control_Title = lv_label_create(ui_settings);
    lv_obj_set_width(ui_Light_Control_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Light_Control_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Light_Control_Title, 0);
    lv_obj_set_y(ui_Light_Control_Title, -36);
    lv_obj_set_align(ui_Light_Control_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Light_Control_Title, "Light Control");
    lv_obj_set_style_text_font(ui_Light_Control_Title, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch_to_clock = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_Switch_to_clock, 50);
    lv_obj_set_height(ui_Switch_to_clock, 50);
    lv_obj_set_x(ui_Switch_to_clock, 10);
    lv_obj_set_y(ui_Switch_to_clock, 10);
    lv_obj_add_flag(ui_Switch_to_clock, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Switch_to_clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Switch_to_clock, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch_to_clock, lv_color_hex(0xE30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_to_clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Switch_to_clock, &ui_img_exit_32_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LED_Brightness_Slider = lv_slider_create(ui_settings);
    lv_slider_set_value(ui_LED_Brightness_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LED_Brightness_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_LED_Brightness_Slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LED_Brightness_Slider, 150);
    lv_obj_set_height(ui_LED_Brightness_Slider, 10);
    lv_obj_set_x(ui_LED_Brightness_Slider, 0);
    lv_obj_set_y(ui_LED_Brightness_Slider, 140);
    lv_obj_set_align(ui_LED_Brightness_Slider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LED_Brightness_Slider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LED_Brightness_Slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LED_Brightness_Slider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LED_Brightness_Slider, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_LED_Brightness_Slider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LED_Brightness_Slider, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LED_Brightness_Slider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LED_Brightness_Slider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LED_Brightness_Slider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LED_Brightness_Slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LED_Brightness_Slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Go_to_terminal = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_Go_to_terminal, 50);
    lv_obj_set_height(ui_Go_to_terminal, 50);
    lv_obj_set_x(ui_Go_to_terminal, 10);
    lv_obj_set_y(ui_Go_to_terminal, 70);
    lv_obj_add_flag(ui_Go_to_terminal, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Go_to_terminal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Go_to_terminal, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Go_to_terminal, lv_color_hex(0x00E300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Go_to_terminal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Go_to_terminal, &ui_img_terminal_32_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Blynk_connect = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_Blynk_connect, 50);
    lv_obj_set_height(ui_Blynk_connect, 50);
    lv_obj_set_x(ui_Blynk_connect, -10);
    lv_obj_set_y(ui_Blynk_connect, 10);
    lv_obj_set_align(ui_Blynk_connect, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Blynk_connect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Blynk_connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Blynk_connect, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Blynk_connect, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Blynk_connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Blynk_connect, &ui_img_blynk_disconnected_50_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Blynk_connect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Blynk_connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Blynk_connect, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Blynk_connect, 25, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_Blynk_connect, lv_color_hex(0xD1FF39), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_Blynk_connect, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_img_src(ui_Blynk_connect, &ui_img_blynk_connected_50_png, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_img_recolor(ui_Blynk_connect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_img_recolor_opa(ui_Blynk_connect, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Go_to_time_settings = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_Go_to_time_settings, 50);
    lv_obj_set_height(ui_Go_to_time_settings, 50);
    lv_obj_set_x(ui_Go_to_time_settings, 10);
    lv_obj_set_y(ui_Go_to_time_settings, 130);
    lv_obj_add_flag(ui_Go_to_time_settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Go_to_time_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Go_to_time_settings, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Go_to_time_settings, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Go_to_time_settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Go_to_time_settings, &ui_img_calendar_32_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Go_to_alarm_settings = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_Go_to_alarm_settings, 50);
    lv_obj_set_height(ui_Go_to_alarm_settings, 50);
    lv_obj_set_x(ui_Go_to_alarm_settings, 10);
    lv_obj_set_y(ui_Go_to_alarm_settings, 190);
    lv_obj_add_flag(ui_Go_to_alarm_settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Go_to_alarm_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Go_to_alarm_settings, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Go_to_alarm_settings, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Go_to_alarm_settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Go_to_alarm_settings, &ui_img_alarm_32_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Go_to_audio_settings = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_Go_to_audio_settings, 50);
    lv_obj_set_height(ui_Go_to_audio_settings, 50);
    lv_obj_set_x(ui_Go_to_audio_settings, 10);
    lv_obj_set_y(ui_Go_to_audio_settings, 250);
    lv_obj_add_flag(ui_Go_to_audio_settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Go_to_audio_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Go_to_audio_settings, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Go_to_audio_settings, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Go_to_audio_settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Go_to_audio_settings, &ui_img_audio_32_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Go_to_network_settings = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_Go_to_network_settings, 50);
    lv_obj_set_height(ui_Go_to_network_settings, 50);
    lv_obj_set_x(ui_Go_to_network_settings, -10);
    lv_obj_set_y(ui_Go_to_network_settings, 190);
    lv_obj_set_align(ui_Go_to_network_settings, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Go_to_network_settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Go_to_network_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Go_to_network_settings, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Go_to_network_settings, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Go_to_network_settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Go_to_network_settings, &ui_img_network_32_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Go_to_files = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_Go_to_files, 50);
    lv_obj_set_height(ui_Go_to_files, 50);
    lv_obj_set_x(ui_Go_to_files, -10);
    lv_obj_set_y(ui_Go_to_files, 250);
    lv_obj_set_align(ui_Go_to_files, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Go_to_files, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Go_to_files, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Go_to_files, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Go_to_files, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Go_to_files, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Go_to_files, &ui_img_folder_32_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings_title = lv_label_create(ui_settings);
    lv_obj_set_width(ui_Settings_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings_title, 0);
    lv_obj_set_y(ui_Settings_title, -140);
    lv_obj_set_align(ui_Settings_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings_title, "Settings");
    lv_obj_set_style_text_font(ui_Settings_title, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LED_Color_Wheel, ui_event_LED_Color_Wheel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LED_Saturation_Slider, ui_event_LED_Saturation_Slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LED_Toggle_Button, ui_event_LED_Toggle_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch_to_clock, ui_event_Switch_to_clock, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LED_Brightness_Slider, ui_event_LED_Brightness_Slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Go_to_terminal, ui_event_Go_to_terminal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Blynk_connect, ui_event_Blynk_connect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Go_to_time_settings, ui_event_Go_to_time_settings, LV_EVENT_ALL, NULL);

}

void ui_settings_screen_destroy(void)
{
    if(ui_settings) lv_obj_del(ui_settings);

    // NULL screen variables
    ui_settings = NULL;
    ui_LED_Color_Wheel = NULL;
    ui_LED_Saturation_Slider = NULL;
    ui_LED_Toggle_Button = NULL;
    ui_Light_Control_Title = NULL;
    ui_Switch_to_clock = NULL;
    ui_LED_Brightness_Slider = NULL;
    ui_Go_to_terminal = NULL;
    ui_Blynk_connect = NULL;
    ui_Go_to_time_settings = NULL;
    ui_Go_to_alarm_settings = NULL;
    ui_Go_to_audio_settings = NULL;
    ui_Go_to_network_settings = NULL;
    ui_Go_to_files = NULL;
    ui_Settings_title = NULL;

}
