// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: custom_clock_2

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settings
extern void ui_settings_screen_init(void);
extern void ui_settings_screen_destroy(void);
extern lv_obj_t * ui_settings;
extern void ui_event_LED_Color_Wheel(lv_event_t * e);
extern lv_obj_t * ui_LED_Color_Wheel;
extern void ui_event_LED_Saturation_Slider(lv_event_t * e);
extern lv_obj_t * ui_LED_Saturation_Slider;
extern void ui_event_LED_Toggle_Button(lv_event_t * e);
extern lv_obj_t * ui_LED_Toggle_Button;
extern lv_obj_t * ui_Light_Control_Title;
extern void ui_event_Switch_to_clock(lv_event_t * e);
extern lv_obj_t * ui_Switch_to_clock;
extern void ui_event_LED_Brightness_Slider(lv_event_t * e);
extern lv_obj_t * ui_LED_Brightness_Slider;
extern void ui_event_Go_to_terminal(lv_event_t * e);
extern lv_obj_t * ui_Go_to_terminal;
extern void ui_event_Blynk_connect(lv_event_t * e);
extern lv_obj_t * ui_Blynk_connect;
extern void ui_event_Go_to_time_settings(lv_event_t * e);
extern lv_obj_t * ui_Go_to_time_settings;
extern lv_obj_t * ui_Go_to_alarm_settings;
extern lv_obj_t * ui_Go_to_audio_settings;
extern lv_obj_t * ui_Go_to_network_settings;
extern lv_obj_t * ui_Go_to_files;
extern lv_obj_t * ui_Settings_title;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

