// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: custom_clock_2

#ifndef UI_TERMINAL_H
#define UI_TERMINAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_terminal
extern void ui_terminal_screen_init(void);
extern void ui_terminal_screen_destroy(void);
extern lv_obj_t * ui_terminal;
extern void ui_event_Terminal_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_Terminal_Keyboard;
extern void ui_event_Switch_to_settings(lv_event_t * e);
extern lv_obj_t * ui_Switch_to_settings;
extern lv_obj_t * ui_Terminal_text_area;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

