// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: custom_clock_2

#include "ui.h"

lv_obj_t * ui_terminal = NULL;
lv_obj_t * ui_Terminal_Keyboard = NULL;
lv_obj_t * ui_Switch_to_settings = NULL;
lv_obj_t * ui_Terminal_text_area = NULL;
// event funtions
void ui_event_Terminal_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        terminalSendCommand(e);
    }
}

void ui_event_Switch_to_settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_OUT_TOP, 500, 0, &ui_settings_screen_init);
    }
}

// build funtions

void ui_terminal_screen_init(void)
{
    ui_terminal = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_terminal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Terminal_Keyboard = lv_keyboard_create(ui_terminal);
    lv_obj_set_width(ui_Terminal_Keyboard, 430);
    lv_obj_set_height(ui_Terminal_Keyboard, 120);
    lv_obj_set_align(ui_Terminal_Keyboard, LV_ALIGN_BOTTOM_RIGHT);

    ui_Switch_to_settings = lv_btn_create(ui_terminal);
    lv_obj_set_width(ui_Switch_to_settings, 50);
    lv_obj_set_height(ui_Switch_to_settings, 114);
    lv_obj_set_x(ui_Switch_to_settings, 0);
    lv_obj_set_y(ui_Switch_to_settings, -3);
    lv_obj_set_align(ui_Switch_to_settings, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Switch_to_settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Switch_to_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Switch_to_settings, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch_to_settings, lv_color_hex(0xE30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch_to_settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Switch_to_settings, &ui_img_exit_32_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Terminal_text_area = lv_textarea_create(ui_terminal);
    lv_obj_set_width(ui_Terminal_text_area, 480);
    lv_obj_set_height(ui_Terminal_text_area, 200);
    lv_obj_set_align(ui_Terminal_text_area, LV_ALIGN_TOP_MID);
    lv_textarea_set_placeholder_text(ui_Terminal_text_area, "Type 'help' for commands");
    lv_obj_clear_flag(ui_Terminal_text_area, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Terminal_text_area, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Terminal_text_area, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_Terminal_Keyboard, ui_Terminal_text_area);
    lv_obj_add_event_cb(ui_Terminal_Keyboard, ui_event_Terminal_Keyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch_to_settings, ui_event_Switch_to_settings, LV_EVENT_ALL, NULL);

}

void ui_terminal_screen_destroy(void)
{
    if(ui_terminal) lv_obj_del(ui_terminal);

    // NULL screen variables
    ui_terminal = NULL;
    ui_Terminal_Keyboard = NULL;
    ui_Switch_to_settings = NULL;
    ui_Terminal_text_area = NULL;

}
